name: Collect Tweets About Climate

on:
  push:
    branches:
      - main

jobs:
  collect_tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m venv venv  # Cria o ambiente virtual
          source venv/bin/activate  # Ativa o ambiente virtual
          python -m pip install --upgrade pip
          pip install -r requerimentos.txt  # Instala as dependências

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requerimentos.txt  # Instala as dependências dentro do ambiente virtual

      - name: Run the tweet collection script
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python coleta-twitter.py
