name: Coleta de Dados do Twitter

on:
  schedule:
    - cron: '0 9 * * *'  # Rodar todos os dias às 9 AM
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  coleta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar script de coleta
        run: python coleta_twitter.py
